### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by Janniboy951** [peteole/economySim#2]

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 1

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 2

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 3

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 4

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 5

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 6

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 7

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 8

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 9

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 10

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 11

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 12

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 13

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 14

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 15

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 16

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 17

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 18

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 19

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 20

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 21

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 22

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 23

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 24

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 25

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 26

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 27

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 28

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 29

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 30

**Comment by Janniboy951** [comment]
Ich aergere Ole Nr. 31

**Comment by peteole** [comment]
Jan, mental 13, hat gelernt, was eine API ist :)
